DEVKITPRO ?= /opt/devkitpro
include $(DEVKITPRO)/3ds_rules

TARGET      := sandbox
BUILD       := build
SOURCES     := Source
INCLUDES    := ../Tiny3D/Source   # 👈 Engine headers here
LIBDIRS     := ../Tiny3D/build

CFLAGS      := -g -O2 -Wall -DARM11 -D_3DS
CXXFLAGS    := $(CFLAGS) -fno-rtti -fno-exceptions
ARCH        := -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft

LIBS        := -ltiny3d -lcitro2d -lcitro3d -lctru -lm

.PHONY: all clean
all: $(TARGET).3dsx

clean:
	rm -rf $(BUILD) $(TARGET).3dsx $(TARGET).elf $(TARGET).smdh
